-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."languages" add column "is_main" boolean
--  not null default 'false';
