version: '3.6'
services:
  authorizer:
    # image: ghcr.io/aura-nw/authorizer:0.1.16
    image: quochai194/authorizer:0.1.22.1
    # image: lakhansamani/authorizer:1.1.50
    restart: always
    ports:
      - '8090:8090'
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
    environment:
      ENV: production
      DATABASE_TYPE: postgres
      DATABASE_URL: postgres://postgres:pkmrmf9Rh4GPaXMx@postgres:5432/postgres
      ADMIN_SECRET: BtfpvmBDJ8b3SGsw
      ORGANIZATION_NAME: AuraNetwork
      ORGANIZATION_LOGO: 'https://aura-explorer-assets.s3.ap-southeast-1.amazonaws.com/aura.png'
      DEFAULT_ROLES: user
      PROTECTED_ROLES: admin
      ACCESS_TOKEN_EXPIRY_TIME: 3h
      CUSTOM_ACCESS_TOKEN_SCRIPT: function(user,tokenPayload) {var data = tokenPayload;  data['https://hasura.io/jwt/claims'] = {'x-hasura-user-id':user.id,'x-hasura-default-role':tokenPayload.allowed_roles[0], 'x-hasura-allowed-roles':user.roles  };  return data;}
      ZALO_APP_ID: 2318977898294005000
      ZALO_APP_SECRET: JmS4L81B99c5cp2sbnSw
      PORT: 8090
      LOG_LEVEL: debug
