-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE VIEW chapter_total_likes AS
--   SELECT chapter_id, count(1)
--     FROM likes
--     GROUP BY chapter_id;
