-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."manga" add column "publish_date" timestamptz
--  null default now();
