-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."story_character" add column "story_event_submission" integer
--  null;
