-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION total_creator_subscribers(creator_row creators) RETURNS
-- int
-- AS $$
--     SELECT COUNT(1) as total_subscribers FROM public.subscribers
--     INNER JOIN manga_creator mc on subscribers.manga_id = mc.manga_id
--     WHERE mc.creator_id = creator_row.id
-- $$ LANGUAGE sql STABLE;
