-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."story_collection_for_access_protocol" add column "description" varchar
--  null;
