-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."chapters" add column "pushlish_date" timestamptz
--  not null default now();
