-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."custodial_wallet_address" add column "address_type" text
--  null;
