name: Deploy hasura - staging
on:
  push:
    branches:
      - staging
jobs:
  hasura_migration:
    name: Hasura migration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Apply hasura migrations
        uses: tibotiber/hasura-action@master # use a tagged version instead of master
        with:
          args: deploy --endpoint $HASURA_ENDPOINT --admin-secret $HASURA_ADMIN_SECRET
        env:
          HASURA_ENDPOINT: ${{ secrets.HASURA_STAGING_ENDPOINT }}
          HASURA_ADMIN_SECRET: ${{ secrets.HASURA_STAGING_ADMIN_SECRET }}
          HASURA_WORKDIR: hasura # replace this by your own path if needed
          HASURA_ENGINE_VERSION: v2.6.2 # replace this by the version you need, remove to use stable
