-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."authorizer_users" add column "ton_wallet_address" text
--  null;
